### ISSUE TITLE
Disqualification isn't working properly

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-guilds-service#11]
I've been posting orders from the default guild member on the UI for more than 30 minutes and I'm still part of the guild:

https://devnet.api.injective.dev/guilds/6242d5a20cf464a8d2bdbc7e

**Comment by achilleas-kal** [comment]
Disqualifications are working as expected, I believe I was testing with the default guild member yesterday but should be normal member.

**Comment by vinhphuctadang** [comment]
> Disqualifications are working as expected, I believe I was testing with the default guild member yesterday but should be normal member.

Since we want default member (us) to be there to track overall performance, we can't let it go. Thanks Achilleas
