### ISSUE TITLE
Historical returns don't update and constantly show as 0.00%

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-guilds-service#12]
The historical returns for my guild show as 0.00% but I've been trading for more than 30 minutes now.

<img width="596" alt="image" src="https://user-images.githubusercontent.com/83584143/160625565-a3d1a12c-e254-46b9-9ee4-d6a7f0ba1b5a.png">

https://devnet.api.injective.dev/guilds/6242d5a20cf464a8d2bdbc7e

**Comment by vinhphuctadang** [comment]
It is zero because: On FE, if default member's first snapshot is zero then it will be zero all the time.
- From BE, what I will do is force the default member to have some balance before adding
- FE can do a workaround like looking for first non-zero snapshot

**Comment by achilleas-kal** [comment]
Hey @vinhphuctadang, the portfolio update interval is set to 1h:

1) I created a guild with a default member that had 10k USDT in the wallet
2) Transferred 5k USDT shortly after and was expecting to see 50% returns after the update

The returns still show as 0 after 1h+ and the guild was created after the member had already 10k USDT, see here for a more accurate picture:

https://devnet.explorer.injective.dev/account/inj1e9r02vp2d25tv7mjc3thd8pslj29hlddtm3q6h

**Comment by achilleas-kal** [comment]
This got updated but I wonder why returns are 91%, any ideas? @vinhphuctadang 

![image](https://user-images.githubusercontent.com/83584143/161052114-61575379-48d0-4bf4-85ba-14774ff85f92.png)

**Comment by vinhphuctadang** [comment]
It's miscalculated from FE
`(last-first)/first/day*365`, not `(last-first)/first/hour*365`
I'll sync with Thomas to fix this

**Comment by vinhphuctadang** [comment]
FE updated, please check if you catch some times @achilleas-kal

**Comment by achilleas-kal** [comment]
Hey @vinhphuctadang, I still don't think the returns are accurate. I took the exact same steps above and when I looked in the guild it was 180% but not sure if maybe there had been more than one "snapshots" I tried changing the portfolio snapshot to 10m but the returns take more than an hour to reflect.

Can you let me know how to change the interval for the returns so I can test this more accurately?

![image](https://user-images.githubusercontent.com/83584143/161597361-90bdc6b4-2022-4eab-b155-057288024d09.png)

**Comment by Tofel** [comment]
I can still see the original issue... and my default member had 1000 USDT on the trading account, when the guild was created, but returns are still 0.0% after transferring out 500 USDT.

![image](https://user-images.githubusercontent.com/20401585/161705603-1d2b4f1c-4b32-47c4-9f3b-a6300b270898.png)

**Comment by vinhphuctadang** [comment]
FE had updated this, but now a little problem with the APY formula

**Comment by achilleas-kal** [comment]
Fixed, returns show properly now.
