### ISSUE TITLE
Prevent users from creating duplicate guild names

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-guilds-service#13]
![Sohnelder](https://user-images.githubusercontent.com/83584143/160628406-437cef29-35c5-4cad-90b3-9454a01e0fde.png)

Duplicate guild names should not be allowed.

**Comment by vinhphuctadang** [comment]
https://github.com/InjectiveLabs/injective-guilds-service/pull/25 should fix this
We will see something like 👇  when we create duplicate name:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/30641530/160987273-6996307a-8843-411d-b3b0-1ab945ce9ce6.png">

Btw, this is from our end so I don't really worry atm.

**Comment by achilleas-kal** [comment]
Hey @vinhphuctadang, yes just making sure it won't affect us in the future eventually this should be open to everyone.

I was able to create a duplicate one, have we updated the binary on devnet?

![image](https://user-images.githubusercontent.com/83584143/161032889-c8c900d5-123f-4993-994e-5ecb8baa4cb8.png)

**Comment by vinhphuctadang** [comment]
I forgot to rebuild it on devnet. Rebuilt with latest dev now. 
It should work now. Thanks

**Comment by vinhphuctadang** [comment]
The problem must relate to:
+ Unrealized PNL, we don't check for open position for default members.
+ INJ price fluctuation
+ (Not likely) FE miscalculation, FE fixed, I will reproduce to see if the problem still persists, https://github.com/InjectiveLabs/injective-guilds-service/issues/12.

Thanks Achilleas

**Comment by vinhphuctadang** [comment]
Built+tested, atm we accept case sensitive

**Comment by achilleas-kal** [comment]
Fixed!
