### ISSUE TITLE
Validation for message types isn't working properly

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-guilds-service#14]
I've already provided authorization for this message type and I'm not allowed to join the guild

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/83584143/160640496-ab60bdb1-2f02-4fb3-bd4e-8c3870609764.png">

**Comment by vinhphuctadang** [comment]
Can you double check this, as we can successfully joined a guild with API

**Comment by achilleas-kal** [comment]
Hey Phuc, indeed not sure why that happened but everything works normally now. Closing the issue.
