### ISSUE TITLE
"Member not found" when trying to join a guild

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-guilds-service#16]
I get this error back when I try to join a guild

![image](https://user-images.githubusercontent.com/83584143/160662095-ccfa5415-5ef6-4748-aa9f-2beb50399ad2.png)

![image](https://user-images.githubusercontent.com/83584143/160662243-7193f10b-40d4-4096-bad4-3a0be8b5a2be.png)

**Comment by vinhphuctadang** [comment]
Not sure why, I didn't throw that error on backend tbh. Please double check if it still occurs

**Comment by achilleas-kal** [comment]
yeah that was fixed after the latest FE pushes not sure on what the issue was but not on the backend side, closing.
