### ISSUE TITLE
Improve error message on maximum guild capacity

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-guilds-service#20]
Hey Phuc, can we modify this message to something like "Max guild capacity has been reached" or something like that?

It's not very clear now.

![image](https://user-images.githubusercontent.com/83584143/160800874-e7b79b58-94c6-4799-aeb8-6e11676927d9.png)

**Comment by vinhphuctadang** [comment]
This should improves the problem. 👇 
https://github.com/InjectiveLabs/injective-guilds-service/pull/22
