### ISSUE TITLE
Newly created guild shows negative returns before a second snapshot takes place

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-guilds-service#26]
![image](https://user-images.githubusercontent.com/83584143/161033719-9398a617-2f6a-418b-a5e7-394e7cc661fe.png)

https://devnet.guild.injective.dev/guild/62457f6ba7732f3f7ffa3676

**Comment by vinhphuctadang** [comment]
Should be a FE problem. BE didn't calculate any APY

**Comment by achilleas-kal** [comment]
Fixed.
