### ISSUE TITLE
We do not remove the snapshot when user leaves the guild

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-guilds-service#31]
Compare these two screenshots.

First one shows the state right after joining with 449 USDT in trading account.
<img width="598" alt="image" src="https://user-images.githubusercontent.com/20401585/161599951-9f4b120e-1331-4583-83e9-4288ac1984a6.png">

Second one when joining with 209 USDT in trading account.
<img width="624" alt="image" src="https://user-images.githubusercontent.com/20401585/161601500-b204ae91-cf92-4150-93e1-b3593c4ae720.png">

Not to mention having negative earnings and returns right after joining.

**Comment by vinhphuctadang** [comment]
Should be fixed in this commit: https://github.com/InjectiveLabs/injective-guilds-service/commit/4d78374cecbf0936d365793164d7e2c0843da103

**Comment by Tofel** [comment]
Fixed ✅
