### ISSUE TITLE
Handle deleted guilds better

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-guilds-service#34]
**Steps to reproduce**
1. Create a guild.
2. Open it's overview page (e.g. `/guild/624af4a6dc2fb2d74c953c78/`)
3. Delete the guild via CLI
4. Open it's overview page again

Expected result:
1. 404 page displayed or redirection to home page.

Actual result: 
<img width="752" alt="image" src="https://user-images.githubusercontent.com/20401585/161700903-9d5c0fc9-fb2e-4ca6-96b6-8bffd594ed2a.png">

Related to: https://github.com/InjectiveLabs/injective-guilds-service/issues/32

Maybe it would be best if BE returned a 404 in such case and then FE would handle it gently by redirecting to home page? Currently that `/guild/<guid>` route returns a 404 for a guid that never existed, but for guilds that did exist it returns in an empty page with error message...

**Comment by Tofel** [comment]
In general I wonder what should we do with orders/positions opened by the guild when it is deleted? Currently nothing happens and they are left opened, but maybe we should close them?

**Comment by vinhphuctadang** [comment]
Hey, I had a quick fix, please check on the devnet. @Tofel please help check when you catch sometimes

**Comment by Tofel** [comment]
I think it is good enough ✅
