### ISSUE TITLE
Update portfolio snapshot when guild member joins or leaves guild

### ISSUE THREAD

**Issue by cmhchoi** [InjectiveLabs/injective-guilds-service#41]
Currently, we are only updating the portfolio value of the guild at a set interval. Which is fine but when there are members joining or leaving the guild and seeing the portfolio value not being updated, it may create a illusion that the portfolio is not responsive.

**Comment by vinhphuctadang** [comment]
There are many solutions to deal with this but for sake of implement simplicity + performance i will go with naive method 1

https://www.notion.so/injective/Guild-V2-features-WIP-01ddc66a1ea947a18038743a7f1f3ada#3a2dd994216947e7a37585b2bd5ab607

Basically, when user join guild, it adds the member's snapshot to current latest snapshot of the guild, same with leave (but subtract)

It has potential of inconsistency for the next snapshot if people join/leave guild at the time snapshot happens, but if we treat portfolio as an overview then it's fine. Snapshot will be auto corrected on next interval

**Comment by vinhphuctadang** [comment]
It should be handled from BE so I transferred the issue

**Comment by vinhphuctadang** [comment]
This PR should solve https://github.com/InjectiveLabs/injective-guilds-service/pull/42. Moving to QA

**Comment by vinhphuctadang** [comment]
Deployed to devnet

**Comment by achilleas-kal** [comment]
Works great when you join the guild but it's not updated when you leave the guild.

**Comment by Tofel** [comment]
Works good ✅
