### ISSUE TITLE
Default guild member should grant rights to the master

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-guilds-service#6]
The default member doesn't grant rights to the guild master upon guild creation but it should.

**Comment by vinhphuctadang** [comment]
https://github.com/InjectiveLabs/injective-guilds-service/pull/23 should check for granted permissions before creating guild.
To be honest, it's from our side so no much worries about this

**Comment by achilleas-kal** [comment]
Cool, closing then!
